#! /usr/bin/perl -w

 print "# generated by usys.pl - do not edit\n";
 print "#include \"syscall.h\"\n";
 print "#include \"riscv.h\"\n";
 print ".section .text\n";
 print ".globl ";

@syscalls = qw(
fork
exit
wait
pipe
read
kill
exec
fstat
chdir
dup
getpid
sbrk
sleep
uptime
open
write
mknod
unlink
link
mkdir
close
yield
);

for my $i (0 .. $#syscalls) {
  if($i != 0) {
    print ",";
  }
  print "sys_$syscalls[$i]";
}
print "\n";

foreach my $name (@syscalls) {
  print ".globl $name\n";
  print "$name:\n";
  print "  li a7, SYS_" . $name . "\n";
  print "  ecall\n";
  print "  ret\n\n";
}
